## **Importing the libraries**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# **Importing the dataset**

In [2]:
dataset = pd.read_csv('ACME-Happiness1Survey2020.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[3 3 3 4 2 4]
 [3 2 3 5 4 3]
 [5 3 3 3 3 5]
 [5 4 3 3 3 5]
 [5 4 3 3 3 5]
 [5 5 3 5 5 5]
 [3 1 2 2 1 3]
 [5 4 4 4 4 5]
 [4 1 4 4 4 4]
 [4 4 4 2 5 5]
 [3 2 3 3 2 3]
 [4 4 3 4 4 4]
 [5 2 4 5 5 5]
 [4 2 4 5 4 3]
 [4 1 3 3 4 3]
 [3 2 4 3 4 4]
 [5 3 4 5 4 5]
 [5 1 4 3 4 5]
 [5 1 2 4 4 5]
 [4 2 4 4 4 4]
 [4 2 3 3 4 4]
 [4 3 5 5 5 4]
 [4 3 5 5 5 4]
 [5 1 2 5 2 4]
 [4 3 3 3 3 4]
 [3 4 3 3 2 3]
 [3 3 3 5 5 5]
 [3 3 1 3 3 4]
 [3 3 1 3 3 4]
 [5 3 3 3 5 3]
 [5 3 3 3 5 3]
 [4 1 3 4 4 5]
 [3 2 4 4 4 5]
 [3 2 4 4 4 5]
 [4 1 3 1 1 4]
 [4 2 3 3 4 4]
 [5 3 4 3 4 5]
 [5 3 4 3 4 5]
 [5 2 3 3 2 5]
 [4 4 3 4 2 4]
 [5 2 3 3 3 3]
 [4 2 4 3 2 4]
 [5 2 3 3 4 5]
 [4 3 3 4 2 4]
 [3 1 2 4 3 5]
 [5 3 4 4 4 5]
 [5 3 3 4 4 5]
 [1 1 1 3 1 4]
 [5 2 5 5 5 3]
 [5 1 3 3 4 4]
 [5 1 3 3 4 4]
 [5 1 3 3 4 4]
 [5 2 4 3 4 5]
 [5 2 4 3 4 5]
 [4 3 2 4 3 4]
 [4 3 2 4 3 4]
 [5 1 1 5 3 5]
 [4 4 4 4 3 4]
 [5 3 5 5 4 5]
 [5 2 4 2 2 4]
 [4 3 3 3 3 5]
 [5 2 4 4 5 5]
 [5 2 4 4 5 5]
 [5 5 5 2 5 5]
 [4 1 3 4 4 4]
 [4 1 3 4 4 4]
 [3 3 3 5 

In [4]:
print(y)

[0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 1 1 0 0 1 1 1 0 1
 1 1 1 0 1 0 0 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 0 1 1 0 1 1 0 0 1 1 1 0 1 0
 1 0 0 1 0 1 1 0 1 1 0 1 1 0 0 0 0 1 1 1 0 1 0 1 1 0 1 1 0 1 0 1 1 0 0 1 0
 0 0 0 0 0 1 1 1 1 0 1 1 1 0 0]


# **Splitting the dataset into the Training set and Test set**

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# **Feature Scaling**

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
print(X_train)

[[-1.59578202  1.34567699  0.71234775  1.45957729 -2.39185652 -1.63056169]
 [-0.37762781 -0.47280543  0.71234775  1.45957729  0.31590558 -1.63056169]
 [-1.59578202 -0.47280543  0.71234775  0.31030383  0.31590558  0.89744093]
 [-1.59578202 -0.47280543 -0.27702412 -0.83896962  0.31590558 -0.36656038]
 [-1.59578202  0.43643578 -0.27702412  1.45957729  1.21849294  0.89744093]
 [-0.37762781  1.34567699  0.71234775  0.31030383 -2.39185652 -1.63056169]
 [ 0.84052641 -0.47280543  0.71234775  0.31030383  1.21849294  0.89744093]
 [-0.37762781  0.43643578 -0.27702412 -0.83896962 -0.58668179  0.89744093]
 [ 0.84052641  0.43643578 -1.26639599  1.45957729  1.21849294  0.89744093]
 [ 0.84052641  0.43643578 -0.27702412 -0.83896962 -1.48926915  0.89744093]
 [ 0.84052641  1.34567699 -0.27702412 -0.83896962 -0.58668179  0.89744093]
 [-1.59578202  0.43643578 -0.27702412  1.45957729  0.31590558 -1.63056169]
 [-1.59578202 -1.38204664 -1.26639599 -1.98824308 -2.39185652 -1.63056169]
 [ 0.84052641 -0.47280543

In [8]:
print(X_test)

[[-0.37762781 -1.38204664  0.71234775  0.31030383  0.31590558 -0.36656038]
 [ 0.84052641 -1.38204664 -0.27702412 -0.83896962  0.31590558 -0.36656038]
 [-0.37762781  0.43643578 -0.27702412  0.31030383 -1.48926915 -0.36656038]
 [-0.37762781  0.43643578 -0.27702412 -0.83896962 -0.58668179 -0.36656038]
 [ 0.84052641  2.2549182   1.70171961 -1.98824308  1.21849294  0.89744093]
 [-1.59578202  0.43643578 -1.26639599  0.31030383  0.31590558 -0.36656038]
 [-0.37762781  0.43643578 -1.26639599  0.31030383 -0.58668179 -0.36656038]
 [ 0.84052641 -1.38204664 -0.27702412  0.31030383  1.21849294  0.89744093]
 [ 0.84052641  1.34567699  0.71234775  0.31030383  0.31590558  0.89744093]
 [-0.37762781 -1.38204664 -0.27702412 -0.83896962 -0.58668179 -0.36656038]
 [-1.59578202 -0.47280543 -0.27702412 -0.83896962 -1.48926915 -1.63056169]
 [-0.37762781  2.2549182   1.70171961  1.45957729 -2.39185652 -1.63056169]
 [-0.37762781 -0.47280543 -0.27702412  0.31030383 -0.58668179 -1.63056169]
 [ 0.84052641 -0.47280543

# **Decision Tree Classification model**

# **Training the Decision Tree Classification model on the Training set**

In [9]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [10]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [1 0]]


# **Making the Confusion Matrix**

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[7 6]
 [7 6]]


0.5

# **K-Nearest Neighbors (K-NN)**

# **Training the K-NN model on the Training set**

In [12]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 10, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [13]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]]


# **Making the Confusion Matrix**

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 7  6]
 [ 3 10]]


0.6538461538461539

# **Support Vector Machine (SVM)**

# **Training the SVM model on the Training set**

In [15]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [16]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]]


# **Making the Confusion Matrix**

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 8  5]
 [ 1 12]]


0.7692307692307693

# **Kernel SVM**

# **Training the Kernel SVM model on the Training set**

In [18]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [19]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]]



# **Making the Confusion Matrix** 

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[5 8]
 [5 8]]


0.5

# **Logistic Regression**


# **Training the Logistic Regression model on the Training set**

In [21]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [22]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]]


# **Making the Confusion Matrix**

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 5  8]
 [ 2 11]]


0.6153846153846154

# **Naive Bayes**

# **Training the Naive Bayes model on the Training set**

In [24]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [25]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]]


# **Making the Confusion Matrix**

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 6  7]
 [ 3 10]]


0.6153846153846154

# **Random Forest Classification**

# **Training the Random Forest Classification model on the Training set**

In [27]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [28]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]]


# **Making the Confusion Matrix**

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[5 8]
 [4 9]]


0.5384615384615384

# **Evaluation**
Among all classification algorithms which i have implemented SVM is generating very good accuracy score which is 76 percent. so for these dataset svm is the best for predicting whether customer is happy or not.